spring.application.name=due-diligence-agent

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/realestate
spring.datasource.username=postgres
spring.datasource.password=191217@Ss
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=12345678912345678912345678912345
jwt.expiration=86400000
# Google Geocoding API
# ATTOM API
attom.api-key=test12345678

# REGRID API
regrid.api-token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZWdyaWQuY29tIiwiaWF0IjoxNzg3NDgwNDk3LCJleHAiOjE3OTAwNzI0OTcsInUiOjg3MDU1MiwiZyI6MjMxNTMsImNhcCI6InBhOnRzOnBzOmJmOm1hOnR5OmVvOnpvOnNiIn0.p3pRoi4WO4PXMjD0R315NkYGvTKz2rVbrxOmOXf5lVU
# FEMA NFHL API
FEMA_NFHL_BASE_URL=https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer
EPA_ENVIROFACTS_BASE_URL=https://frs-public.epa.gov/ords/frs_public2/frs_rest_services.get_facilities
SHOVELS_API_KEY=dZ4Gq6UBX6jydJar1NnwFH_hZ6pbx6EpBDTbUPe7bC4
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG